[package]
name = "buzz"
version = "1.1.10"

description = "A simple system tray application for notifying about unseen e-mail"
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

homepage = "https://github.com/jonhoo/buzz"
repository = "https://github.com/jonhoo/buzz.git"

keywords = ["email","cli","systray","notification"]
categories = ["command-line-utilities", "email"]

license = "MIT/Apache-2.0"

[badges]
maintenance = { status = "passively-maintained" }

[profile.release]
debug=true

[dependencies]
imap = "1.0"
native-tls = "0.2"
# systray = "0.3.0"
mailparse = "0.8"
toml = "0.5"
xdg = "2.1.0"
notify-rust = "3.4.0"
rayon = "1.0.0"
# askama_escape = "0.2"
chrono = "0.4"
